export const fonts = {
  heading: "'Bebas Neue', cursive",
  body: "'Sora', sans-serif",
  mono: "'IBM Plex Mono', monospace",
};

export const colors = {
  bg: "var(--sip-bg)",
  card: "var(--sip-card)",
  cardBorder: "var(--sip-card-border)",
  inputBg: "var(--sip-input-bg)",
  inputBorder: "var(--sip-input-border)",
  subtleBorder: "var(--sip-subtle-border)",
  text: "var(--sip-text)",
  textMuted: "var(--sip-text-muted)",
  textDim: "var(--sip-text-dim)",
  textDimmer: "var(--sip-text-dimmer)",
  textDimmest: "var(--sip-text-dimmest)",
  textGhost: "var(--sip-text-ghost)",
  accent: "var(--sip-accent)",
  success: "var(--sip-success)",
  error: "var(--sip-error)",
  hoverCard: "var(--sip-hover-card)",
};

export const shared = {
  label: {
    fontFamily: fonts.mono,
    fontSize: 10,
    color: colors.textDimmer,
    letterSpacing: 3,
  },
  sectionLabel: {
    fontFamily: fonts.mono,
    fontSize: 11,
    color: colors.textDim,
    letterSpacing: 2,
    fontWeight: 600,
  },
  tinyLabel: {
    fontFamily: fonts.mono,
    fontSize: 10,
    color: colors.textDimmer,
    letterSpacing: 2,
    marginBottom: 6,
  },
  input: {
    width: "100%",
    background: colors.inputBg,
    border: `1px solid ${colors.inputBorder}`,
    borderRadius: 8,
    padding: "12px 14px",
    color: colors.text,
    fontSize: 15,
    fontFamily: fonts.body,
    outline: "none",
    boxSizing: "border-box",
  },
  card: {
    background: colors.card,
    border: `1px solid ${colors.cardBorder}`,
    borderRadius: 14,
  },
  cancelBtn: {
    background: "none",
    border: `1px solid ${colors.subtleBorder}`,
    color: colors.textDimmer,
    borderRadius: 6,
    padding: "7px 14px",
    fontSize: 11,
    cursor: "pointer",
    fontFamily: fonts.mono,
  },
  backBtn: {
    background: "none",
    border: "none",
    color: colors.textDimmer,
    cursor: "pointer",
    fontFamily: fonts.mono,
    fontSize: 12,
    letterSpacing: 1,
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: 0,
  },
};
