export const fonts = {
  heading: "'Bebas Neue', cursive",
  body: "'Sora', sans-serif",
  mono: "'IBM Plex Mono', monospace",
};

export const colors = {
  bg: "#09090D",
  card: "#111118",
  cardBorder: "#1A1A22",
  inputBg: "#1A1A26",
  inputBorder: "#252535",
  subtleBorder: "#2A2A38",
  text: "#EEE8E0",
  textMuted: "#CCC",
  textDim: "#888",
  textDimmer: "#555",
  textDimmest: "#444",
  textGhost: "#333",
  accent: "#F0B429",
  success: "#34D399",
  error: "#F87171",
};

export const shared = {
  label: {
    fontFamily: fonts.mono,
    fontSize: 10,
    color: colors.textDimmer,
    letterSpacing: 3,
  },
  sectionLabel: {
    fontFamily: fonts.mono,
    fontSize: 11,
    color: colors.textDim,
    letterSpacing: 2,
    fontWeight: 600,
  },
  tinyLabel: {
    fontFamily: fonts.mono,
    fontSize: 10,
    color: colors.textDimmer,
    letterSpacing: 2,
    marginBottom: 6,
  },
  input: {
    width: "100%",
    background: colors.inputBg,
    border: `1px solid ${colors.inputBorder}`,
    borderRadius: 8,
    padding: "12px 14px",
    color: colors.text,
    fontSize: 15,
    fontFamily: fonts.body,
    outline: "none",
    boxSizing: "border-box",
  },
  card: {
    background: colors.card,
    border: `1px solid ${colors.cardBorder}`,
    borderRadius: 14,
  },
  cancelBtn: {
    background: "none",
    border: `1px solid ${colors.subtleBorder}`,
    color: colors.textDimmer,
    borderRadius: 6,
    padding: "7px 14px",
    fontSize: 11,
    cursor: "pointer",
    fontFamily: fonts.mono,
  },
  backBtn: {
    background: "none",
    border: "none",
    color: colors.textDimmer,
    cursor: "pointer",
    fontFamily: fonts.mono,
    fontSize: 12,
    letterSpacing: 1,
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: 0,
  },
};
